# Generated by Django 4.2.2 on 2023-06-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='post',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.CharField(max_length=100),
        ),
    ]
