# Generated by Django 4.2.2 on 2023-06-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_feedback_post_alter_services_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
